language: ruby
cache: bundler
rvm:
  - 1.9.3
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
notifications:
  email:
    recipients:
      - edgarhinshunlee@gmail.com
    on_failure: change
    on_success: never
