# Travis-CI Build for broggle
# see travis-ci.org for details

language: ruby

# Ruby versions to test against
rvm:
  - 1.9.3

script: script/travisbuild

notifications:
  email:
    recipients:
      - edgarhinshunlee@gmail.com
    on_failure: change
    on_success: never
